name: Bug Report
description: Report a bug or an error
title: "[Bug] <Enter title here>"
labels: ["bug"]
assignees: []
body:
  - type: textarea
    id: describe
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: "The game crashes when I..."
    validations:
      required: true
  - type: textarea
    id: howtoreproduce
    attributes:
      label: "To Reproduce"
      description: "Steps to reproduce the behavior:"
      placeholder: |
        1. Join the server from 1.14.4
        2. Duel a player.
        3. Do ???.
        4. I've been kicked.
    validations:
      required: true
  - type: input
    id: logs
    attributes:
      label: "Screenshots/Videos"
      description: "Provide a link to additional screenshots/videos that may help solve the problem."
    validations:
      required: false
