name: Feature Request
description: Suggest a feature or an improvement for the server
title: "[Feature] <Enter title here>"
labels: ["feature"]
assignees: []
body:
  - type: textarea
    id: solution
    attributes:
      label: "Describe the feature"
      description: "A clear description of the possibly-related problem and of the suggesten."
      placeholder: "e.g. An option on the PvP gamemode to make bow boosting (like in 1.12.2) with the optional difficulty configuration."
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature here."
      placeholder: "e.g. Also I'd like an option to disable modern bow boosting."
    validations:
      required: false
